# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Synonym', max_length=255)),
                ('description', models.ManyToManyField(to='animationfinder.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animationfinder.Item')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='item',
            field=models.ManyToManyField(blank=True, to='animationfinder.Item'),
        ),
    ]
