# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Animation', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Synonym', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('animations', models.ManyToManyField(blank=True, to='animationfinder.Animation')),
            ],
        ),
    ]
